-- SQL Schema per il database di Monica Fiocco
-- Da incollare ed eseguire nel pannello "SQL Editor" di Supabase (https://supabase.com)

-- 1. Tabella Articoli
CREATE TABLE IF NOT EXISTS articles (
  slug TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL,
  read_time TEXT NOT NULL,
  excerpt TEXT,
  image TEXT,
  author TEXT NOT NULL DEFAULT 'Monica Fiocco',
  is_featured BOOLEAN NOT NULL DEFAULT false,
  is_favorite BOOLEAN NOT NULL DEFAULT false,
  content TEXT,
  order_priority INTEGER DEFAULT 10,
  tags TEXT[] DEFAULT '{}',
  is_event BOOLEAN NOT NULL DEFAULT false,
  featured_end_date TEXT,
  auto_indexing BOOLEAN NOT NULL DEFAULT true,
  is_top_featured BOOLEAN NOT NULL DEFAULT false,
  top_featured_end_date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabella Categorie
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Disabilita RLS per consentire accesso in lettura/scrittura semplice (o configura le policy)
-- Supabase consiglia RLS attivo, ma per un'integrazione immediata senza autenticazione utenti Supabase,
-- possiamo abilitare l'accesso pubblico in lettura/scrittura.
ALTER TABLE articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
